export { default as express } from "./about/express.png";
export { default as postman } from "./about/postman.png";
export { default as github } from "./about/github.png";
export { default as instagram } from "./about/instagram.png";
export { default as whatsapp } from "./about/whatsapp.png";
export { default as linkedin } from "./about/linkedin.png";
export { default as postgresql } from "./about/postgresql.png";
export { default as react } from "./about/react.png";
export { default as tailwindcss } from "./about/tailwindcss.png";
